videos:
  list:
    - file-id: "BAACAgIAAxkBAAMZXoOw_cPJNqozO1cOUuVR4Xt-H9gAAngCAAKD4alL5Fno2Vgix_gYBA"
      file-unique-id: "AgADeAIAAoPhqUs"
      keywords:
        - "сложно"
        - "карина"
        - "hard"
        - "complex"
    - file-id: "BAACAgQAAxkBAAMbXoOxS5PcPMeol4akb_-Ma-yzS00AAtgBAALoYJVTjbIiurstDD0YBA"
      file-unique-id: "AgAD2AEAAuhglVM"
      keywords:
        - "что происходит"
        - "wtf"
    - file-id: "BAACAgQAAxkBAAMdXoOxY9XAMqMr7LBxCXE-zWI_Bn0AAv0BAALIV5xTAal5iE4JXgABGAQ"
      file-unique-id: "AgAD_QEAAshXnFM"
      keywords:
        - "пиздец"
        - "зоопарк"
        - "смешно"
    - file-id: "BAACAgQAAxkBAAMfXoOxiI7BmvAStnsBtJJTBfP2XLAAAgoCAAKyFOVTrO7RQoVf43UYBA"
      file-unique-id: "AgADCgIAArIU5VM"
      keywords:
        - "вы че ебанутые"
        - "ебанутые"
        - "ебнутые"
        - "ёбнутые"
    - file-id: "BAACAgQAAxkBAAMhXoOx_vyRHgPyqU-TvjKenDDALB4AAhgCAAI9SWxTKQl41qOzI3QYBA"
      file-unique-id: "AgADGAIAAj1JbFM"
      keywords:
        - "ты дурак"
        - "дурак"
    - file-id: "BAACAgQAAxkBAAMjXoOyER2pjZ0x4JuyIyW7HYZbQvwAAjgCAAIcs4RTjOhwWYj5sLUYBA"
      file-unique-id: "AgADOAIAAhyzhFM"
      keywords:
        - "врете"
        - "врёте"
    - file-id: "BAACAgIAAxkBAAMlXoO1vrb1U9EyKrk6YlUs0oOzDIcAAi8FAAI9tJlIao3aqyHgLp0YBA"
      file-unique-id: "AgADLwUAAj20mUg"
      keywords:
        - "сделал"
        - "готово"
        - "done"

