videos:
  list:
    - file-id: "BAACAgIAAxkBAAMZXoOw_cPJNqozO1cOUuVR4Xt-H9gAAngCAAKD4alL5Fno2Vgix_gYBA"
      file-unique-id: "AgADeAIAAoPhqUs"
      keywords:
        - "сложно"
        - "карина"
        - "hard"
        - "complex"
    - file-id: "BAACAgQAAxkBAAMbXoOxS5PcPMeol4akb_-Ma-yzS00AAtgBAALoYJVTjbIiurstDD0YBA"
      file-unique-id: "AgAD2AEAAuhglVM"
      keywords:
        - "что происходит"
        - "wtf"
    - file-id: "BAACAgQAAxkBAAMdXoOxY9XAMqMr7LBxCXE-zWI_Bn0AAv0BAALIV5xTAal5iE4JXgABGAQ"
      file-unique-id: "AgAD_QEAAshXnFM"
      keywords:
        - "пиздец"
        - "зоопарк"
        - "смешно"
    - file-id: "BAACAgQAAxkBAAMfXoOxiI7BmvAStnsBtJJTBfP2XLAAAgoCAAKyFOVTrO7RQoVf43UYBA"
      file-unique-id: "AgADCgIAArIU5VM"
      keywords:
        - "вы че ебанутые"
        - "ебанутые"
        - "ебнутые"
        - "ёбнутые"
    - file-id: "BAACAgQAAxkBAAMhXoOx_vyRHgPyqU-TvjKenDDALB4AAhgCAAI9SWxTKQl41qOzI3QYBA"
      file-unique-id: "AgADGAIAAj1JbFM"
      keywords:
        - "ты дурак"
        - "дурак"
    - file-id: "BAACAgQAAxkBAAMjXoOyER2pjZ0x4JuyIyW7HYZbQvwAAjgCAAIcs4RTjOhwWYj5sLUYBA"
      file-unique-id: "AgADOAIAAhyzhFM"
      keywords:
        - "врете"
        - "врёте"
    - file-id: "BAACAgIAAxkBAAMlXoO1vrb1U9EyKrk6YlUs0oOzDIcAAi8FAAI9tJlIao3aqyHgLp0YBA"
      file-unique-id: "AgADLwUAAj20mUg"
      keywords:
        - "сделал"
        - "готово"
        - "done"
    - file-id: "BAACAgIAAxkBAAM1XoTOgLTc7FzOspWi-Ke5awdEngMAApAFAAJy5yhIEaFy-p5ll5kYBA"
      file-unique-id: "AgADkAUAAnLnKEg"
      keywords:
        - "ты за меня придурка не держи"
        - "гамаз"
        - "само собой"
        - "понял"
    - file-id: "BAACAgIAAxkBAAM3XoTQo4hltGt6B-z9Pd0NAAExzog9AAKTBQACcucoSB95sHYyvGrmGAQ"
      file-unique-id: "AgADkwUAAnLnKEg"
      keywords:
        - "це пізда"
        - "пізда"
        - "пизда"
        - "пиздец"
        - "ппц"
        - "пц"
        - "капец"
        - "omg"
    - file-id: "BAACAgIAAxkBAAM5XoTR63eA5xZelYJXQXRlGJEvEysAApQFAAJy5yhI9FePGOeH5VEYBA"
      file-unique-id: "AgADlAUAAnLnKEg"
      keywords:
        - "как все запущено"
        - "запущено"
        - "ооо"
    - file-id: "BAACAgIAAxkBAAM7XoTUJzymAf674CLnsvZYgiaulawAApUFAAJy5yhIIvNINgkBOzAYBA"
      file-unique-id: "AgADlQUAAnLnKEg"
      keywords:
        - "сильное заявление"
        - "дружко"
    - file-id: "BAACAgIAAxkBAAM9XoTVfOXoHlQPDp1ldQ9Q6DDGp2gAApsFAAJy5yhI4PU5t_djAAEBGAQ"
      file-unique-id: "AgADmwUAAnLnKEg"
      keywords:
        - "шо ты там делаешь"
        - "ебанутый"
    - file-id: "BAACAgIAAxkBAAM_XoTWXyWZOGDPyK-E6Yk6ZDxdKKoAApwFAAJy5yhImXFIGkfRbicYBA"
      file-unique-id: "AgADnAUAAnLnKEg"
      keywords:
        - "сказочный долбоеб"
        - "долбоёб"
    - file-id: "BAACAgIAAxkBAANBXoTXnx9VIuRXlEbG4F-KBC17WFIAAp0FAAJy5yhIdiEqa3durH8YBA"
      file-unique-id: "AgADnQUAAnLnKEg"
      keywords:
        - "правильно"
        - "сталин"
        - "right"
        - "correct"
    - file-id: "BAACAgIAAxkBAANOXoUQsuK-4RL-svmTUKtGdk29ZFYAAsAFAAJy5yhIjhVpjPWet9wYBA"
      file-unique-id: "AgADwAUAAnLnKEg"
      keywords:
        - "ну бред же"
        - "бред"
    - file-id: "BAACAgIAAxkBAANQXoURPicXixbqwEu4Nd-o3a6XbWkAAvcFAAJNkyhI09L6fM-tiV8YBA"
      file-unique-id: "AgAD9wUAAk2TKEg"
      keywords:
        - "господи допоможи"
        - "господи помоги"
        - "господи"
        - "тимошенко"
    - file-id: "BAACAgIAAxkBAANSXoUR3W1gre_LOHg7A3n4UtO4BUUAAvgFAAJNkyhISJszZ62X1YUYBA"
      file-unique-id: "AgAD-AUAAk2TKEg"
      keywords:
        - "до пизды этот продукт"
        - "похуй"
    - file-id: "BAACAgIAAxkBAANUXoUSQ9vufn9QQHApQf1CtdP0uwQAAgQGAAJNkyhIIsmwou4gpHEYBA"
      file-unique-id: "AgADBAYAAk2TKEg"
      keywords:
        - "ну пока"
        - "bye"
        - "see you"
        - "до скорого"
    - file-id: "BAACAgQAAxkBAANWXoUTg2PWzXJxy_n5IkvUDn9HPxoAAjsAA1Hy9VCS_oQQ5aqe0xgE"
      file-unique-id: "AgADOwADUfL1UA"
      keywords:
        - "всё"
        - "все"
        - "путин"
    - file-id: "BAACAgIAAxkBAANYXoUU-hE3WAoVXbHeBtOILxo61kAAAsEFAAJy5yhI4Hm4awl_K6oYBA"
      file-unique-id: "AgADwQUAAnLnKEg"
      keywords:
        - "естественно"
        - "конечно"
        - "sure"
        - "да"
        - "yes"
    - file-id: "BAACAgIAAxkBAANaXoUVukmFGyHvzJXpAAEoF0SRTlj-AALCBQACcucoSBOReaWKDbFKGAQ"
      file-unique-id: "AgADwgUAAnLnKEg"
      keywords:
        - "мне насрать"
        - "мне пофиг"
        - "мне все равно"
    - file-id: "BAACAgIAAxkBAANcXoUWYAdBp9-FLzAYYvFxuu1o9WwAAsMFAAJy5yhIoj_UWHHOyT4YBA"
      file-unique-id: "AgADwwUAAnLnKEg"
      keywords:
        - "крик ааа"
    - file-id: "BAACAgIAAxkBAANeXoUWzTNAeTKckpbCh3yAM8JEmTAAAsQFAAJy5yhI9ghuIAOZThwYBA"
      file-unique-id: "AgADxAUAAnLnKEg"
      keywords:
        - "не понял, но интересно"
        - "непонятно"
    - file-id: "BAACAgIAAxkBAANgXoUXee57fcutSdMBOb8jNNRkqqAAAsUFAAJy5yhIiRsrwWiiCWwYBA"
      file-unique-id: "AgADxQUAAnLnKEg"
      keywords:
        - "ты че дурак"
        - "ты чё дурак"
        - "ты дурак"
    - file-id: "BAACAgIAAxkBAANiXoUYJDspkC97m3PjzzRQTe3yK0QAAsYFAAJy5yhIvmUZ0Xq8mVwYBA"
      file-unique-id: "AgADxgUAAnLnKEg"
      keywords:
        - "мы в дерьме"
        - "все плохо"
        - "всё плохо"
        - "очень плохо"
