
videos:
  list:
    - id: "BAACAgIAAxkBAAMZXoOw_cPJNqozO1cOUuVR4Xt-H9gAAngCAAKD4alL5Fno2Vgix_gYBA"
      keywords:
        - "сложно"
        - "карина"
        - "hard"
        - "complex"
    - id: "BAACAgQAAxkBAAMbXoOxS5PcPMeol4akb_-Ma-yzS00AAtgBAALoYJVTjbIiurstDD0YBA"
      keywords:
        - "что происходит"
        - "wtf"
    - id: "BAACAgQAAxkBAAMdXoOxY9XAMqMr7LBxCXE-zWI_Bn0AAv0BAALIV5xTAal5iE4JXgABGAQ"
      keywords:
        - "пиздец"
        - "зоопарк"
        - "смешно"
    - id: "BAACAgQAAxkBAAMfXoOxiI7BmvAStnsBtJJTBfP2XLAAAgoCAAKyFOVTrO7RQoVf43UYBA"
      keywords:
        - "вы че ебанутые"
        - "ебанутые"
        - "ебнутые"
        - "ёбнутые"
    - id: "BAACAgQAAxkBAAMhXoOx_vyRHgPyqU-TvjKenDDALB4AAhgCAAI9SWxTKQl41qOzI3QYBA"
      keywords:
        - "ты дурак"
        - "дурак"
    - id: "BAACAgQAAxkBAAMjXoOyER2pjZ0x4JuyIyW7HYZbQvwAAjgCAAIcs4RTjOhwWYj5sLUYBA"
      keywords:
        - "врете"
        - "врёте"
    - id: "BAACAgIAAxkBAAMlXoO1vrb1U9EyKrk6YlUs0oOzDIcAAi8FAAI9tJlIao3aqyHgLp0YBA"
      keywords:
        - "сделал"
        - "готово"
        - "done"

