server:
  address: 127.0.0.1
  port: 8080

spring:
  profiles:
    include: "videos"

  main.web-application-type: none # don't run web context now since we use polling for bot

#logging:
#  level:
#    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: TRACE

logRestRequestWebInterceptor:
  enabled: true

s3:
  bucket: bucket-name-tbd
  accessKey: EXTERNAL
  secretKey: EXTERNAL
  region: us-west-1
  endpoint: https://s3.us-west-1.wasabisys.com

elk:
  host: elk.cmlteam.com
  port: 10443
  application: video_reply_telegram_bot

telegram-bot:
  admin_user: EXTERNAL
  token: EXTERNAL
  